#!/bin/bash

DIR="$(dirname "$(readlink -f "$0")")"
source "$DIR/../../docker.include.sh"

docker run -it --rm \
    -p 9001:9001 \
    -v "$PWD":/opt/project \
    -v "$HOME/.composer:$HOME/.composer" \
    -w /opt/project -u $UID:${GROUPS[0]} \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v /tmp:/tmp \
    -e TZ=America/Sao_Paulo \
    -v "$HOME/.ssh:$HOME/.ssh" \
    -v "$HOME/.keys:$HOME/.keys:ro" `linkContainer` ${EXTRA_PARAM} \
    byjg/php7:alpine php -d error_reporting=6143 "$@"

